// Generated by https://quicktype.io

import { ImageType, MainInfo, UserPop } from "./intakes.reports";
import { ScoreNum } from "./interfaces";

export interface AllLifeTestResponse {
    ok:          boolean;
    page:        number;
    totalPages:  number;
    allLifeTest: LifeTest[];
}

export interface FilterLifeTest {
    ok:          boolean;
    page:        number;
    totalPages:  number;
    result: LifeTest[];
}

export interface SingleLifeTestResponse {
    ok:         boolean;
    msg:        string;
    singleLife: LifeTest;
}

export interface LifeTest {
    grower:    string;
    palletRef: string;
    score:     ScoreNum;
    status:    boolean;
    _id:       string;
    reportId:  ReportID;
    test:      Test[];
    user:      UserPop;
    date:      string;
}

export interface ReportID {
    _id:      string;
    mainData: MainInfo;
}

export interface Test {
    conditions:  string[];
    temperature: string;
    _id:         string;
    day:         number;
    images:      ImageType[];
    day_date:    string;
}


