// Generated by https://quicktype.io

export type Rol = "ADMIN_ROLE"
| "USER_ROLE"
| "QC_ROLE"
| "CLIENT_ROLE"
| "SUPPLIER_ROLE"

export interface LoginData {
    email: string;
    password: string;
}

export interface RegisterData {
    name: string,
    lastname: string,
    email: string,
    password: string,
    company?: string
}

export interface LoginResponse {
    ok: boolean;
    token: string;

    uid: string,
    name: string,
    lastname: string,
    profile: string,
    company: string,
    contacts: Contact[],
    rol: Rol
}

export interface User {
    uid: string;
    name: string;
    lastname?: string;
    email?: string;
    rol?: string;
    profile: string;
    company?: string;
    contacts?: Contact[] | [];
}

export interface Contact {
    id: string;
    supplier: string;
    ref: string;
    contactName: string;
    email: string;
}
